### ISSUE TITLE
Login Page: Forgot Password Send Button State

### ISSUE THREAD

**Issue by Carl-Tabuso** [BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem#115]
## Non-Urgent

While the magic happens in the SMTP server sending an email to a user, there is no indicator that the email is actually being sent aside from the disable state of the "Send Email" button. See video below

https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/029a615f-6b52-45cd-afe4-e8191e353b31

We can make use of a preloader already built in Bootstrap. @biellamariscotes  @Jeremie-Legrama  @bobbymorante what do you think?

**Comment by biellamariscotes** [comment]
A simple spinner preloader is suitable for indicating that an email is being sent. We will finalize the design with the UI team. For now, here's a conceptual idea of what it might look like:

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/135019439/540f786b-4cdd-4785-a462-1d50ba8b5245)

There will also be a text below the animation, like:

**Your email is being sent.**
**Please wait a moment.**
