### ISSUE TITLE
File Import and Export

### ISSUE THREAD

**Issue by Carl-Tabuso** [BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem#258]
Allowance of CSV or XLSX file import of organization's member master list.

**Comment by LZionDEVQA** [comment]
How can I install a php library to our system? Do I have a permission to install a php library or other devs will do it?

phpspreadsheet library is required to make the file import/export work. It is needed for csv and xlsx file.

**Comment by Carl-Tabuso** [comment]
> How can I install a php library to our system? Do I have a permission to install a php library or other devs will do it?

> phpspreadsheet library is required to make the file import/export work. It is needed for csv and xlsx file.

You might want to check on Edan and Benedict about the PHP spreadsheet library. They might be using the same thing for the election reports page for exporting a report in .pdf .xlsx .csv. 

If not, you may install code libraries/packages in the `vendor/` folder on your local computer. And then, you can just push them to save everyone's time the chore of doing the installation again. Document it properly on your pull request—what is the library called, usage, and other things alike, and how was it implemented in our project. 


Hope this answers your question.

**Comment by LZionDEVQA** [comment]
Thank you for the response
