### ISSUE TITLE
[ENHANCEMENT]: Duplicate entries on voter importing

### ISSUE THREAD

**Issue by make-sundae** [BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem#287]
- CSV and Excel files can be imported, even if they contain duplicate entries. However, the system will only add unique voter entries to the database. Duplicate entries will be ignored during the import process.
- After the import, a list of ignored duplicate entries will be displayed in a modal.

**Comment by Carl-Tabuso** [comment]
UP @Andrei-Matibag
