### ISSUE TITLE
Registration Page Footer

### ISSUE THREAD

**Issue by Carl-Tabuso** [BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem#97]
The footer of the registration page is not aligned with what's on the landing page. To boot, JMAP is not included in the list of organizations. We can't afford this discrepancy next presentation.

**Landing Page:**

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/78b01e79-11e6-4110-a46d-afc6782794ea)

**Registration Page (JMAP is missing):**

![image](https://github.com/BSIT-3-1-APPDEV/PUPSRC-AutomatedElectionSystem/assets/162773681/05f10372-d1c8-45b6-a385-c4c1591a357f)

**Comment by biellamariscotes** [comment]
I'll attach a branch that addresses this UI inaccuracy in a future PR.
